# stadiums_store.py

stadium_data = [
    {
        "StadiumID": 1,
        "StadiumName": "Angel Stadium",
        "City": "Anaheim",
        "State": "California",
        "Latitude": 33.80019044,
        "Longitude": -117.8823996,
        "FieldInfo": "",
        "CompassBearing": 41.67,
        "OutdoorOnly": "Yes"
    },
    {
        "StadiumID": 2,
        "StadiumName": "Oriole Park at Camden Yards",
        "City": "Baltimore",
        "State": "Maryland",
        "Latitude": 39.283787,
        "Longitude": -76.621689,
        "FieldInfo": "",
        "CompassBearing": 31.47,
        "OutdoorOnly": "Yes"
    },
    {
        "StadiumID": 3,
        "StadiumName": "Fenway Park",
        "City": "Boston",
        "State": "Massachusetts",
        "Latitude": 42.346456,
        "Longitude": -71.097441,
        "FieldInfo": "",
        "CompassBearing": 44.74,
        "OutdoorOnly": "Yes"
    },
    {
        "StadiumID": 4,
        "StadiumName": "Rate Field",
        "City": "Chicago",
        "State": "Illinois",
        "Latitude": 41.83,
        "Longitude": -87.634167,
        "FieldInfo": "",
        "CompassBearing": 126.91,
        "OutdoorOnly": "Yes"
    },
    {
        "StadiumID": 5,
        "StadiumName": "Progressive Field",
        "City": "Cleveland",
        "State": "Ohio",
        "Latitude": 41.495861,
        "Longitude": -81.685255,
        "FieldInfo": "",
        "CompassBearing": 0,
        "OutdoorOnly": "Yes"
    },
    {
        "StadiumID": 7,
        "StadiumName": "Kauffman Stadium",
        "City": "Kansas City",
        "State": "Missouri",
        "Latitude": 39.051567,
        "Longitude": -94.480483,
        "FieldInfo": "",
        "CompassBearing": 46.73,
        "OutdoorOnly": "Yes"
    },
    {
        "StadiumID": 14,
        "StadiumName": "Rogers Centre",
        "City": "Toronto",
        "State": "Ontario",
        "Latitude": 43.64155,
        "Longitude": -79.38915,
        "FieldInfo": "",
        "CompassBearing": None,
        "OutdoorOnly": "No"
    },
    {
        "StadiumID": 15,
        "StadiumName": "Chase Field",
        "City": "Phoenix",
        "State": "Arizona",
        "Latitude": 33.445302,
        "Longitude": -112.066687,
        "FieldInfo": "",
        "CompassBearing": None,
        "OutdoorOnly": "No"
    },
    {
        "StadiumID": 17,
        "StadiumName": "Wrigley Field",
        "City": "Chicago",
        "State": "Illinois",
        "Latitude": 41.948171,
        "Longitude": -87.655503,
        "FieldInfo": "",
        "CompassBearing": 39.50,
        "OutdoorOnly": "Yes"
    },
    {
        "StadiumID": 19,
        "StadiumName": "Coors Field",
        "City": "Denver",
        "State": "Colorado",
        "Latitude": 39.756042,
        "Longitude": -104.994136,
        "FieldInfo": "",
        "CompassBearing": 4.81,
        "OutdoorOnly": "Yes"
    },
    {
        "StadiumID": 22,
        "StadiumName": "Dodger Stadium",
        "City": "Los Angeles",
        "State": "California",
        "Latitude": 34.07368,
        "Longitude": -118.24053,
        "FieldInfo": "",
        "CompassBearing": 26.5,
        "OutdoorOnly": "Yes"
    },
    {
        "StadiumID": 31,
        "StadiumName": "PNC Park",
        "City": "Pittsburgh",
        "State": "Pennsylvania",
        "Latitude": 40.446904,
        "Longitude": -80.005753,
        "FieldInfo": "",
        "CompassBearing": 115.77,
        "OutdoorOnly": "Yes"
    },
    {
        "StadiumID": 32,
        "StadiumName": "American Family Field",
        "City": "Milwaukee",
        "State": "Wisconsin",
        "Latitude": 43.02838,
        "Longitude": -87.97099,
        "FieldInfo": "",
        "CompassBearing": 129.5,
        "OutdoorOnly": "No"
    },
    {
        "StadiumID": 680,
        "StadiumName": "T-Mobile Park",
        "City": "Seattle",
        "State": "Washington",
        "Latitude": 47.591333,
        "Longitude": -122.33251,
        "FieldInfo": "",
        "CompassBearing": 48.5,
        "OutdoorOnly": "No"
    },
    {
        "StadiumID": 2602,
        "StadiumName": "Great American Ball Park",
        "City": "Cincinnati",
        "State": "Ohio",
        "Latitude": 39.097389,
        "Longitude": -84.506611,
        "FieldInfo": "",
        "CompassBearing": 122.94,
        "OutdoorOnly": "Yes"
    },
    {
        "StadiumID": 4169,
        "StadiumName": "loanDepot park",
        "City": "Miami",
        "State": "Florida",
        "Latitude": 25.77796236,
        "Longitude": -80.21951795,
        "FieldInfo": "",
        "CompassBearing": 129.3,
        "OutdoorOnly": "No"
    },
    {
        "StadiumID": 2889,
        "StadiumName": "Busch Stadium",
        "City": "St. Louis",
        "State": "Missouri",
        "Latitude": 38.62256667,
        "Longitude": -90.19286667,
        "FieldInfo": "",
        "CompassBearing": 62.07,
        "OutdoorOnly": "Yes"
    },
    {
        "StadiumID": 5325,
        "StadiumName": "Globe Life Field",
        "City": "Arlington",
        "State": "Texas",
        "Latitude": 32.747299,
        "Longitude": -97.081818,
        "FieldInfo": "",
        "CompassBearing": None,
        "OutdoorOnly": "No"
    },
    {
        "StadiumID": 2392,
        "StadiumName": "Daikin Park",
        "City": "Houston",
        "State": "Texas",
        "Latitude": 29.756967,
        "Longitude": -95.355509,
        "FieldInfo": "",
        "CompassBearing": 345.67,
        "OutdoorOnly": "No"
    },
    {
        "StadiumID": 3289,
        "StadiumName": "Citi Field",
        "City": "Flushing",
        "State": "New York",
        "Latitude": 40.75753012,
        "Longitude": -73.84559155,
        "FieldInfo": "",
        "CompassBearing": 13.11,
        "OutdoorOnly": "Yes"
    },
    {
        "StadiumID": 2394,
        "StadiumName": "Comerica Park",
        "City": "Detroit",
        "State": "Michigan",
        "Latitude": 42.3391151,
        "Longitude": -83.048695,
        "FieldInfo": "",
        "CompassBearing": 151.76,
        "OutdoorOnly": "Yes"
    },
    {
        "StadiumID": 2395,
        "StadiumName": "Oracle Park",
        "City": "San Francisco",
        "State": "California",
        "Latitude": 37.778383,
        "Longitude": -122.389448,
        "FieldInfo": "",
        "CompassBearing": 84.77,
        "OutdoorOnly": "Yes"
    },
    {
        "StadiumID": 2523,
        "StadiumName": "George M. Steinbrenner Field",
        "City": "Tampa",
        "State": "Florida",
        "Latitude": 27.97997,
        "Longitude": -82.50702,
        "FieldInfo": "",
        "CompassBearing": 60.39,
        "OutdoorOnly": "Yes"
    },
    {
        "StadiumID": 4705,
        "StadiumName": "Truist Park",
        "City": "Atlanta",
        "State": "Georgia",
        "Latitude": 33.890672,
        "Longitude": -84.467641,
        "FieldInfo": "",
        "CompassBearing": 149,
        "OutdoorOnly": "Yes"
    },
    {
        "StadiumID": 2529,
        "StadiumName": "Sutter Health Park",
        "City": "Sacramento",
        "State": "California",
        "Latitude": 38.57994,
        "Longitude": -121.51246,
        "FieldInfo": "",
        "CompassBearing": 46.68,
        "OutdoorOnly": "Yes"
    },
    {
        "StadiumID": 3309,
        "StadiumName": "Nationals Park",
        "City": "Washington",
        "State": "District of Columbia",
        "Latitude": 38.872861,
        "Longitude": -77.007501,
        "FieldInfo": "",
        "CompassBearing": 28.51,
        "OutdoorOnly": "Yes"
    },
    {
        "StadiumID": 3312,
        "StadiumName": "Target Field",
        "City": "Minneapolis",
        "State": "Minnesota",
        "Latitude": 44.981829,
        "Longitude": -93.277891,
        "FieldInfo": "",
        "CompassBearing": 90,
        "OutdoorOnly": "Yes"
    },
    {
        "StadiumID": 3313,
        "StadiumName": "Yankee Stadium",
        "City": "Bronx",
        "State": "New York",
        "Latitude": 40.82919482,
        "Longitude": -73.9264977,
        "FieldInfo": "",
        "CompassBearing": 75,
        "OutdoorOnly": "Yes"
    },
    {
        "StadiumID": 2680,
        "StadiumName": "Petco Park",
        "City": "San Diego",
        "State": "California",
        "Latitude": 32.707861,
        "Longitude": -117.157278,
        "FieldInfo": "",
        "CompassBearing": 360,
        "OutdoorOnly": "Yes"
    },
    {
        "StadiumID": 2681,
        "StadiumName": "Citizens Bank Park",
        "City": "Philadelphia",
        "State": "Pennsylvania",
        "Latitude": 39.90539086,
        "Longitude": -75.16716957,
        "FieldInfo": "",
        "CompassBearing": 9.41,
        "OutdoorOnly": "Yes"
    }
]
